# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TEg44cw7KxIxzXHrYC0PMmed9am8v0QH
"""

#Write a Python program to reverse a string.
   #Sample String : "1234abcd"
    #Expected Output : "dcba4321"


def reverse(str):
    string = " "
    for i in str:
        string = i + string
    return string
str = input ("Enter the string: ")       #user input
print("\nThe original string is:",str)
print("The reverse string is:", reverse(str))

def reverse(str):
    string = " "
    for i in str:
        string = i + string
    return string
str = input ("Enter the string: ")       #user input
print("\nThe original string is:",str)
print("The reverse string is:", reverse(str))

